controller_list:
  - name: fake_panda1_controller
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: fake_panda2_controller
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: fake_hand1_controller
    joints:
      - panda_1_finger_joint1
  - name: fake_hand2_controller
    joints:
      - panda_2_finger_joint1
  - name: fake_dual_controller
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
initial:  # Define initial robot poses.
  - group: panda1
    pose: random_pose
  - group: hand1
    pose: closed
  - group: hand2
    pose: open
  - group: dual
    pose: test