panda1:
  kinematics_solver: panda_dual_gazebo_panda1/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.1
panda2:
  kinematics_solver: panda_dual_gazebo_panda2/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.1
