controller_list:
  - name: panda_1_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: panda_2_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: panda_1_hand_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    parallel: True
    joints:
        - panda_1_finger_joint1
        - panda_1_finger_joint2
  - name: panda_2_hand_controller
    action_ns: gripper_action
    default: True
    parallel: True
    type: GripperCommand
    joints:
        - panda_2_finger_joint1
        - panda_2_finger_joint2